import { ColorTheme, AppearanceMode, AccessibilityMode } from "../types/app";
import { Appearance } from "react-native";

// ACCESSIBILITY CONSTANTS FOR OLDER ADULTS
// These values ensure WCAG AA compliance minimum 3:1 for UI components

// Input field styling
const INPUT_BORDER_LIGHT = "#AAAAAA"; // Visible border on cream background
const INPUT_BORDER_DARK = "#555555"; // Visible border on dark background

// Toggle switch colors - HIGH VISIBILITY
const TOGGLE_TRACK_OFF_LIGHT = "#D1D5DB"; // Darker gray fill (Gray-300) for better visibility
const TOGGLE_TRACK_OFF_DARK = "#4B5563"; // Dark gray when OFF (dark mode)
const TOGGLE_THUMB = "#FFFFFF"; // White thumb always

// Disabled states - visible but clearly inactive
const BUTTON_DISABLED_LIGHT = "#9CA3AF";
const BUTTON_DISABLED_DARK = "#6B7280";
const BUTTON_DISABLED_TEXT_LIGHT = "#6B7280";
const BUTTON_DISABLED_TEXT_DARK = "#9CA3AF";

// Tab bar colors
const TAB_BAR_INACTIVE_LIGHT = "#6B7280"; // Darker than #999999
const TAB_BAR_INACTIVE_DARK = "#9CA3AF";

// Shared semantic colors for light themes
const LIGHT_SEMANTIC = {
  successBackground: "#E8F5E9",
  warningBackground: "#FEF3C7",
  errorBackground: "#FEE2E2",
  onSuccess: "#2E7D32",
  onWarning: "#92400E",
  onError: "#991B1B",
  premium: "#FFD700",
  premiumLight: "#FFF9E6",
  premiumDark: "#78350F",
  onPremium: "#FFFFFF",
};

// Shared semantic colors for dark themes
const DARK_SEMANTIC = {
  successBackground: "#1A3A2A",
  warningBackground: "#3A2E1A",
  errorBackground: "#3A1A1A",
  onSuccess: "#8CC9AE",
  onWarning: "#FBBF24",
  onError: "#F87171",
  premium: "#FFD700",
  premiumLight: "#3A3520",
  premiumDark: "#FBBF24",
  onPremium: "#1A1A1A",
};

// Shared semantic colors for high contrast themes (light)
const HIGH_CONTRAST_SEMANTIC = {
  successBackground: "#E8F5E9",
  warningBackground: "#FEF3C7",
  errorBackground: "#FEE2E2",
  onSuccess: "#004D26",
  onWarning: "#663D00",
  onError: "#800000",
  premium: "#B8860B",
  premiumLight: "#FFF9E6",
  premiumDark: "#5C4300",
  onPremium: "#FFFFFF",
};

// Shared semantic colors for high contrast themes (dark)
const DARK_HIGH_CONTRAST_SEMANTIC = {
  successBackground: "#0A2E1A",
  warningBackground: "#2E2000",
  errorBackground: "#2E0A0A",
  onSuccess: "#66FF99",
  onWarning: "#FFD666",
  onError: "#FF8888",
  premium: "#FFD700",
  premiumLight: "#2E2800",
  premiumDark: "#FFE066",
  onPremium: "#000000",
};

// Shared semantic colors for colorblind themes (light)
const COLORBLIND_SEMANTIC = {
  successBackground: "#D4E9F7",
  warningBackground: "#FFECD4",
  errorBackground: "#FFE0D4",
  onSuccess: "#004C77",
  onWarning: "#773311",
  onError: "#881100",
  premium: "#FFD700",
  premiumLight: "#FFF9E6",
  premiumDark: "#78350F",
  onPremium: "#FFFFFF",
};

// Shared semantic colors for colorblind themes (dark)
const DARK_COLORBLIND_SEMANTIC = {
  successBackground: "#0A2840",
  warningBackground: "#3A2510",
  errorBackground: "#3A1510",
  onSuccess: "#66BBEE",
  onWarning: "#FFAA66",
  onError: "#FF8866",
  premium: "#FFD700",
  premiumLight: "#3A3520",
  premiumDark: "#FBBF24",
  onPremium: "#1A1A1A",
};

// Surface colors for badges, subtle containers - WCAG AA compliant
const LIGHT_SURFACE = {
  surfaceSubtle: "#F2F2F7", // iOS system gray 6 (light)
  surfaceMuted: "#E5E5EA", // iOS system gray 5 (light)
  borderSubtle: "#D1D1D6", // iOS system gray 4 (light)
};

const DARK_SURFACE = {
  surfaceSubtle: "#3A3A3C", // iOS system gray 5 (dark)
  surfaceMuted: "#48484A", // iOS system gray 4 (dark)
  borderSubtle: "#545456", // iOS system gray 3 (dark)
};

const HIGH_CONTRAST_SURFACE = {
  surfaceSubtle: "#F5F5F5",
  surfaceMuted: "#E0E0E0",
  borderSubtle: "#000000",
};

const DARK_HIGH_CONTRAST_SURFACE = {
  surfaceSubtle: "#1A1A1A",
  surfaceMuted: "#2A2A2A",
  borderSubtle: "#FFFFFF",
};

const DARK_COLORBLIND_SURFACE = {
  surfaceSubtle: "#3A3A3C",
  surfaceMuted: "#48484A",
  borderSubtle: "#545456",
};

export interface ThemeColors {
  // Brand Colors
  primary: string;
  primaryLight: string;
  primaryDark: string;
  onPrimary: string; // Text color on primary buttons (theme-aware)

  // Background Colors
  background: string; // Main background
  cardBackground: string; // Card/container backgrounds
  modalBackground: string; // Modal backgrounds

  // Surface Colors (for badges, subtle containers)
  surfaceSubtle: string; // Subtle surface for badges, helper text boxes
  surfaceMuted: string; // More muted surface
  borderSubtle: string; // Subtle border for badges

  // Text Colors
  textPrimary: string; // Primary text
  textSecondary: string; // Secondary/helper text
  textTertiary: string; // Disabled/placeholder text

  // UI Element Colors
  border: string; // Border color
  divider: string; // Divider lines
  success: string; // Success states
  warning: string; // Warning states
  error: string; // Error states
  info: string; // Info states

  // Semantic Background Colors
  successBackground: string; // Light success background (e.g., #E8F5E9)
  warningBackground: string; // Light warning background (e.g., #FEF3C7)
  errorBackground: string; // Light error background (e.g., #FEE2E2)
  infoBackground: string; // Light info background

  // Text on Semantic Backgrounds
  onSuccess: string; // Text on success backgrounds
  onWarning: string; // Text on warning backgrounds
  onError: string; // Text on error backgrounds
  onInfo: string; // Text on info backgrounds

  // Premium / Gold Colors
  premium: string; // Premium gold color (#FFD700)
  premiumLight: string; // Light premium background (#FFF9E6)
  premiumDark: string; // Dark premium for text (#78350F or #B8860B)
  onPremium: string; // Text on premium buttons (white or dark)

  // Input field styling
  inputBorder: string;
  inputBackground: string;
  inputPlaceholder: string;

  // Toggle switch colors
  toggleTrackOn: string;
  toggleTrackOff: string;
  toggleThumb: string;

  // Disabled states
  buttonDisabled: string;
  buttonDisabledText: string;

  // Tab bar
  tabBarActive: string;
  tabBarInactive: string;

  // Interactive States
  buttonText: string; // Text on primary buttons (DEPRECATED - use onPrimary)
  linkText: string; // Link text

  // Shadow
  shadow: string; // Shadow color

  // Theme Metadata
  name: string;
  description: string;
}

// LIGHT MODE THEMES - Each theme has unique background tint
export const COLOR_THEMES: Record<ColorTheme, ThemeColors> = {
  blue: {
    primary: "#2F80ED",
    primaryLight: "#E5F2FF",
    primaryDark: "#1E5FBF",
    onPrimary: "#FFFFFF",
    background: "#F5F9FF",
    cardBackground: "#FFFFFF",
    modalBackground: "#FFFFFF",
    ...LIGHT_SURFACE,
    textPrimary: "#1A1A1A",
    textSecondary: "#525252",
    textTertiary: "#888888",
    border: "#DDDDDD",
    divider: "#E5E5E5",
    success: "#6DB193",
    warning: "#F59E0B",
    error: "#EF4444",
    info: "#2F80ED",
    ...LIGHT_SEMANTIC,
    infoBackground: "#E5F2FF",
    onInfo: "#1E5FBF",
    inputBorder: INPUT_BORDER_LIGHT,
    inputBackground: "#FFFFFF",
    inputPlaceholder: "#888888",
    toggleTrackOn: "#2563EB",
    toggleTrackOff: TOGGLE_TRACK_OFF_LIGHT,
    toggleThumb: TOGGLE_THUMB,
    buttonDisabled: BUTTON_DISABLED_LIGHT,
    buttonDisabledText: BUTTON_DISABLED_TEXT_LIGHT,
    tabBarActive: "#2F80ED",
    tabBarInactive: TAB_BAR_INACTIVE_LIGHT,
    buttonText: "#FFFFFF",
    linkText: "#2F80ED",
    shadow: "rgba(0, 0, 0, 0.1)",
    name: "Ocean Blue",
    description: "Classic and calming",
  },
  sage: {
    primary: "#6DB193",
    primaryLight: "#E8F5F0",
    primaryDark: "#4F9170",
    onPrimary: "#FFFFFF",
    background: "#F5F9F5",
    cardBackground: "#FFFFFF",
    modalBackground: "#FFFFFF",
    ...LIGHT_SURFACE,
    textPrimary: "#1A1A1A",
    textSecondary: "#525252",
    textTertiary: "#888888",
    border: "#DDDDDD",
    divider: "#E5E5E5",
    success: "#6DB193",
    warning: "#F59E0B",
    error: "#EF4444",
    info: "#2F80ED",
    ...LIGHT_SEMANTIC,
    infoBackground: "#E8F5F0",
    onInfo: "#4F9170",
    inputBorder: INPUT_BORDER_LIGHT,
    inputBackground: "#FFFFFF",
    inputPlaceholder: "#888888",
    toggleTrackOn: "#059669",
    toggleTrackOff: TOGGLE_TRACK_OFF_LIGHT,
    toggleThumb: TOGGLE_THUMB,
    buttonDisabled: BUTTON_DISABLED_LIGHT,
    buttonDisabledText: BUTTON_DISABLED_TEXT_LIGHT,
    tabBarActive: "#6DB193",
    tabBarInactive: TAB_BAR_INACTIVE_LIGHT,
    buttonText: "#FFFFFF",
    linkText: "#6DB193",
    shadow: "rgba(0, 0, 0, 0.1)",
    name: "Sage Green",
    description: "Natural and peaceful",
  },
  purple: {
    primary: "#8B5CF6",
    primaryLight: "#F3EBFF",
    primaryDark: "#7C3AED",
    onPrimary: "#FFFFFF",
    background: "#F8F5FF",
    cardBackground: "#FFFFFF",
    modalBackground: "#FFFFFF",
    ...LIGHT_SURFACE,
    textPrimary: "#1A1A1A",
    textSecondary: "#525252",
    textTertiary: "#888888",
    border: "#DDDDDD",
    divider: "#E5E5E5",
    success: "#6DB193",
    warning: "#F59E0B",
    error: "#EF4444",
    info: "#8B5CF6",
    ...LIGHT_SEMANTIC,
    infoBackground: "#F3EBFF",
    onInfo: "#7C3AED",
    inputBorder: INPUT_BORDER_LIGHT,
    inputBackground: "#FFFFFF",
    inputPlaceholder: "#888888",
    toggleTrackOn: "#7C3AED",
    toggleTrackOff: TOGGLE_TRACK_OFF_LIGHT,
    toggleThumb: TOGGLE_THUMB,
    buttonDisabled: BUTTON_DISABLED_LIGHT,
    buttonDisabledText: BUTTON_DISABLED_TEXT_LIGHT,
    tabBarActive: "#8B5CF6",
    tabBarInactive: TAB_BAR_INACTIVE_LIGHT,
    buttonText: "#FFFFFF",
    linkText: "#8B5CF6",
    shadow: "rgba(0, 0, 0, 0.1)",
    name: "Purple",
    description: "Creative and vibrant",
  },
  orange: {
    primary: "#F59E0B",
    primaryLight: "#FFF4E5",
    primaryDark: "#D97706",
    onPrimary: "#1A1A1A",
    background: "#FFF9ED",
    cardBackground: "#FFFFFF",
    modalBackground: "#FFFFFF",
    ...LIGHT_SURFACE,
    textPrimary: "#1A1A1A",
    textSecondary: "#525252",
    textTertiary: "#888888",
    border: "#DDDDDD",
    divider: "#E5E5E5",
    success: "#6DB193",
    warning: "#F59E0B",
    error: "#EF4444",
    info: "#2F80ED",
    ...LIGHT_SEMANTIC,
    infoBackground: "#FFF4E5",
    onInfo: "#D97706",
    inputBorder: INPUT_BORDER_LIGHT,
    inputBackground: "#FFFFFF",
    inputPlaceholder: "#888888",
    toggleTrackOn: "#D97706",
    toggleTrackOff: TOGGLE_TRACK_OFF_LIGHT,
    toggleThumb: TOGGLE_THUMB,
    buttonDisabled: BUTTON_DISABLED_LIGHT,
    buttonDisabledText: BUTTON_DISABLED_TEXT_LIGHT,
    tabBarActive: "#F59E0B",
    tabBarInactive: TAB_BAR_INACTIVE_LIGHT,
    buttonText: "#1A1A1A",
    linkText: "#F59E0B",
    shadow: "rgba(0, 0, 0, 0.1)",
    name: "Warm Orange",
    description: "Energetic and cheerful",
  },
  pink: {
    primary: "#FF6B6B",
    primaryLight: "#FFE5E5",
    primaryDark: "#E55555",
    onPrimary: "#FFFFFF",
    background: "#FFF5F5",
    cardBackground: "#FFFFFF",
    modalBackground: "#FFFFFF",
    ...LIGHT_SURFACE,
    textPrimary: "#1A1A1A",
    textSecondary: "#525252",
    textTertiary: "#888888",
    border: "#DDDDDD",
    divider: "#E5E5E5",
    success: "#6DB193",
    warning: "#F59E0B",
    error: "#EF4444",
    info: "#2F80ED",
    ...LIGHT_SEMANTIC,
    infoBackground: "#FFE5E5",
    onInfo: "#E55555",
    inputBorder: INPUT_BORDER_LIGHT,
    inputBackground: "#FFFFFF",
    inputPlaceholder: "#888888",
    toggleTrackOn: "#E55555",
    toggleTrackOff: TOGGLE_TRACK_OFF_LIGHT,
    toggleThumb: TOGGLE_THUMB,
    buttonDisabled: BUTTON_DISABLED_LIGHT,
    buttonDisabledText: BUTTON_DISABLED_TEXT_LIGHT,
    tabBarActive: "#FF6B6B",
    tabBarInactive: TAB_BAR_INACTIVE_LIGHT,
    buttonText: "#FFFFFF",
    linkText: "#FF6B6B",
    shadow: "rgba(0, 0, 0, 0.1)",
    name: "Coral",
    description: "Warm and vibrant",
  },
  teal: {
    primary: "#8B5CF6",
    primaryLight: "#EDE9FE",
    primaryDark: "#7C3AED",
    onPrimary: "#FFFFFF",
    background: "#F5F3FF",
    cardBackground: "#FFFFFF",
    modalBackground: "#FFFFFF",
    ...LIGHT_SURFACE,
    textPrimary: "#1A1A1A",
    textSecondary: "#525252",
    textTertiary: "#888888",
    border: "#DDDDDD",
    divider: "#E5E5E5",
    success: "#6DB193",
    warning: "#F59E0B",
    error: "#EF4444",
    info: "#2F80ED",
    ...LIGHT_SEMANTIC,
    infoBackground: "#EDE9FE",
    onInfo: "#7C3AED",
    inputBorder: INPUT_BORDER_LIGHT,
    inputBackground: "#FFFFFF",
    inputPlaceholder: "#888888",
    toggleTrackOn: "#8B5CF6",
    toggleTrackOff: TOGGLE_TRACK_OFF_LIGHT,
    toggleThumb: TOGGLE_THUMB,
    buttonDisabled: BUTTON_DISABLED_LIGHT,
    buttonDisabledText: BUTTON_DISABLED_TEXT_LIGHT,
    tabBarActive: "#8B5CF6",
    tabBarInactive: TAB_BAR_INACTIVE_LIGHT,
    buttonText: "#FFFFFF",
    linkText: "#8B5CF6",
    shadow: "rgba(0, 0, 0, 0.1)",
    name: "Purple",
    description: "Elegant and soothing",
  },
};

// DARK MODE THEMES - Using soft charcoal (#2B2B2B) instead of pure black
export const DARK_COLOR_THEMES: Record<ColorTheme, ThemeColors> = {
  blue: {
    primary: "#4FA3FF",
    primaryLight: "#1E3A5F",
    primaryDark: "#6BB8FF",
    onPrimary: "#1A1A1A",
    background: "#2B2B2B",
    cardBackground: "#363636",
    modalBackground: "#3D3D3D",
    ...DARK_SURFACE,
    textPrimary: "#E8E8E8",
    textSecondary: "#B3B3B3",
    textTertiary: "#808080",
    border: "#4A4A4A",
    divider: "#3D3D3D",
    success: "#8CC9AE",
    warning: "#FBBF24",
    error: "#F87171",
    info: "#4FA3FF",
    ...DARK_SEMANTIC,
    infoBackground: "#1E3A5F",
    onInfo: "#4FA3FF",
    inputBorder: INPUT_BORDER_DARK,
    inputBackground: "#3D3D3D",
    inputPlaceholder: "#808080",
    toggleTrackOn: "#60A5FA",
    toggleTrackOff: TOGGLE_TRACK_OFF_DARK,
    toggleThumb: TOGGLE_THUMB,
    buttonDisabled: BUTTON_DISABLED_DARK,
    buttonDisabledText: BUTTON_DISABLED_TEXT_DARK,
    tabBarActive: "#4FA3FF",
    tabBarInactive: TAB_BAR_INACTIVE_DARK,
    buttonText: "#1A1A1A",
    linkText: "#4FA3FF",
    shadow: "rgba(0, 0, 0, 0.4)",
    name: "Ocean Blue",
    description: "Classic and calming",
  },
  sage: {
    primary: "#8CC9AE",
    primaryLight: "#2A3A33",
    primaryDark: "#A3D4B8",
    onPrimary: "#1A1A1A",
    background: "#2B2B2B",
    cardBackground: "#363636",
    modalBackground: "#3D3D3D",
    ...DARK_SURFACE,
    textPrimary: "#E8E8E8",
    textSecondary: "#B3B3B3",
    textTertiary: "#808080",
    border: "#4A4A4A",
    divider: "#3D3D3D",
    success: "#8CC9AE",
    warning: "#FBBF24",
    error: "#F87171",
    info: "#4FA3FF",
    ...DARK_SEMANTIC,
    infoBackground: "#2A3A33",
    onInfo: "#8CC9AE",
    inputBorder: INPUT_BORDER_DARK,
    inputBackground: "#3D3D3D",
    inputPlaceholder: "#808080",
    toggleTrackOn: "#34D399",
    toggleTrackOff: TOGGLE_TRACK_OFF_DARK,
    toggleThumb: TOGGLE_THUMB,
    buttonDisabled: BUTTON_DISABLED_DARK,
    buttonDisabledText: BUTTON_DISABLED_TEXT_DARK,
    tabBarActive: "#8CC9AE",
    tabBarInactive: TAB_BAR_INACTIVE_DARK,
    buttonText: "#1A1A1A",
    linkText: "#8CC9AE",
    shadow: "rgba(0, 0, 0, 0.4)",
    name: "Sage Green",
    description: "Natural and peaceful",
  },
  purple: {
    primary: "#A78BFA",
    primaryLight: "#3A2A5F",
    primaryDark: "#C4B5FD",
    onPrimary: "#1A1A1A",
    background: "#2B2B2B",
    cardBackground: "#363636",
    modalBackground: "#3D3D3D",
    ...DARK_SURFACE,
    textPrimary: "#E8E8E8",
    textSecondary: "#B3B3B3",
    textTertiary: "#808080",
    border: "#4A4A4A",
    divider: "#3D3D3D",
    success: "#8CC9AE",
    warning: "#FBBF24",
    error: "#F87171",
    info: "#A78BFA",
    ...DARK_SEMANTIC,
    infoBackground: "#3A2A5F",
    onInfo: "#A78BFA",
    inputBorder: INPUT_BORDER_DARK,
    inputBackground: "#3D3D3D",
    inputPlaceholder: "#808080",
    toggleTrackOn: "#A78BFA",
    toggleTrackOff: TOGGLE_TRACK_OFF_DARK,
    toggleThumb: TOGGLE_THUMB,
    buttonDisabled: BUTTON_DISABLED_DARK,
    buttonDisabledText: BUTTON_DISABLED_TEXT_DARK,
    tabBarActive: "#A78BFA",
    tabBarInactive: TAB_BAR_INACTIVE_DARK,
    buttonText: "#1A1A1A",
    linkText: "#A78BFA",
    shadow: "rgba(0, 0, 0, 0.4)",
    name: "Purple",
    description: "Creative and vibrant",
  },
  orange: {
    primary: "#FBBF24",
    primaryLight: "#3A2E1A",
    primaryDark: "#FCD34D",
    onPrimary: "#1A1A1A",
    background: "#2B2B2B",
    cardBackground: "#363636",
    modalBackground: "#3D3D3D",
    ...DARK_SURFACE,
    textPrimary: "#E8E8E8",
    textSecondary: "#B3B3B3",
    textTertiary: "#808080",
    border: "#4A4A4A",
    divider: "#3D3D3D",
    success: "#8CC9AE",
    warning: "#FBBF24",
    error: "#F87171",
    info: "#4FA3FF",
    ...DARK_SEMANTIC,
    infoBackground: "#3A2E1A",
    onInfo: "#FBBF24",
    inputBorder: INPUT_BORDER_DARK,
    inputBackground: "#3D3D3D",
    inputPlaceholder: "#808080",
    toggleTrackOn: "#FBBF24",
    toggleTrackOff: TOGGLE_TRACK_OFF_DARK,
    toggleThumb: TOGGLE_THUMB,
    buttonDisabled: BUTTON_DISABLED_DARK,
    buttonDisabledText: BUTTON_DISABLED_TEXT_DARK,
    tabBarActive: "#FBBF24",
    tabBarInactive: TAB_BAR_INACTIVE_DARK,
    buttonText: "#1A1A1A",
    linkText: "#FBBF24",
    shadow: "rgba(0, 0, 0, 0.4)",
    name: "Warm Orange",
    description: "Energetic and cheerful",
  },
  pink: {
    primary: "#FF8A8A",
    primaryLight: "#3A2525",
    primaryDark: "#FFA5A5",
    onPrimary: "#1A1A1A",
    background: "#2B2B2B",
    cardBackground: "#363636",
    modalBackground: "#3D3D3D",
    ...DARK_SURFACE,
    textPrimary: "#E8E8E8",
    textSecondary: "#B3B3B3",
    textTertiary: "#808080",
    border: "#4A4A4A",
    divider: "#3D3D3D",
    success: "#8CC9AE",
    warning: "#FBBF24",
    error: "#F87171",
    info: "#4FA3FF",
    ...DARK_SEMANTIC,
    infoBackground: "#3A2525",
    onInfo: "#FF8A8A",
    inputBorder: INPUT_BORDER_DARK,
    inputBackground: "#3D3D3D",
    inputPlaceholder: "#808080",
    toggleTrackOn: "#FF8A8A",
    toggleTrackOff: TOGGLE_TRACK_OFF_DARK,
    toggleThumb: TOGGLE_THUMB,
    buttonDisabled: BUTTON_DISABLED_DARK,
    buttonDisabledText: BUTTON_DISABLED_TEXT_DARK,
    tabBarActive: "#FF8A8A",
    tabBarInactive: TAB_BAR_INACTIVE_DARK,
    buttonText: "#1A1A1A",
    linkText: "#FF8A8A",
    shadow: "rgba(0, 0, 0, 0.4)",
    name: "Coral",
    description: "Warm and vibrant",
  },
  teal: {
    primary: "#A78BFA",
    primaryLight: "#2A2540",
    primaryDark: "#C4B5FD",
    onPrimary: "#1A1A1A",
    background: "#2B2B2B",
    cardBackground: "#363636",
    modalBackground: "#3D3D3D",
    ...DARK_SURFACE,
    textPrimary: "#E8E8E8",
    textSecondary: "#B3B3B3",
    textTertiary: "#808080",
    border: "#4A4A4A",
    divider: "#3D3D3D",
    success: "#8CC9AE",
    warning: "#FBBF24",
    error: "#F87171",
    info: "#4FA3FF",
    ...DARK_SEMANTIC,
    infoBackground: "#2A2540",
    onInfo: "#A78BFA",
    inputBorder: INPUT_BORDER_DARK,
    inputBackground: "#3D3D3D",
    inputPlaceholder: "#808080",
    toggleTrackOn: "#A78BFA",
    toggleTrackOff: TOGGLE_TRACK_OFF_DARK,
    toggleThumb: TOGGLE_THUMB,
    buttonDisabled: BUTTON_DISABLED_DARK,
    buttonDisabledText: BUTTON_DISABLED_TEXT_DARK,
    tabBarActive: "#A78BFA",
    tabBarInactive: TAB_BAR_INACTIVE_DARK,
    buttonText: "#1A1A1A",
    linkText: "#A78BFA",
    shadow: "rgba(0, 0, 0, 0.4)",
    name: "Purple",
    description: "Elegant and soothing",
  },
};

// HIGH CONTRAST MODE - Pure white background with maximum contrast
export const HIGH_CONTRAST_THEMES: Record<ColorTheme, ThemeColors> = {
  blue: {
    primary: "#0052CC",
    primaryLight: "#CCE0FF",
    primaryDark: "#003D99",
    onPrimary: "#FFFFFF",
    background: "#FFFFFF",
    cardBackground: "#FFFFFF",
    modalBackground: "#FFFFFF",
    ...HIGH_CONTRAST_SURFACE,
    textPrimary: "#000000",
    textSecondary: "#333333",
    textTertiary: "#666666",
    border: "#000000",
    divider: "#000000",
    success: "#007A3D",
    warning: "#B35900",
    error: "#CC0000",
    info: "#0052CC",
    ...HIGH_CONTRAST_SEMANTIC,
    infoBackground: "#CCE0FF",
    onInfo: "#003D99",
    inputBorder: "#000000",
    inputBackground: "#FFFFFF",
    inputPlaceholder: "#666666",
    toggleTrackOn: "#000000",
    toggleTrackOff: "#666666",
    toggleThumb: TOGGLE_THUMB,
    buttonDisabled: "#666666",
    buttonDisabledText: "#333333",
    tabBarActive: "#000000",
    tabBarInactive: "#333333",
    buttonText: "#FFFFFF",
    linkText: "#0052CC",
    shadow: "rgba(0, 0, 0, 0.3)",
    name: "Ocean Blue",
    description: "Classic and calming",
  },
  sage: {
    primary: "#2D7A52",
    primaryLight: "#CCE8DC",
    primaryDark: "#1F5738",
    onPrimary: "#FFFFFF",
    background: "#FFFFFF",
    cardBackground: "#FFFFFF",
    modalBackground: "#FFFFFF",
    ...HIGH_CONTRAST_SURFACE,
    textPrimary: "#000000",
    textSecondary: "#333333",
    textTertiary: "#666666",
    border: "#000000",
    divider: "#000000",
    success: "#007A3D",
    warning: "#B35900",
    error: "#CC0000",
    info: "#0052CC",
    ...HIGH_CONTRAST_SEMANTIC,
    infoBackground: "#CCE8DC",
    onInfo: "#1F5738",
    inputBorder: "#000000",
    inputBackground: "#FFFFFF",
    inputPlaceholder: "#666666",
    toggleTrackOn: "#000000",
    toggleTrackOff: "#666666",
    toggleThumb: TOGGLE_THUMB,
    buttonDisabled: "#666666",
    buttonDisabledText: "#333333",
    tabBarActive: "#000000",
    tabBarInactive: "#333333",
    buttonText: "#FFFFFF",
    linkText: "#2D7A52",
    shadow: "rgba(0, 0, 0, 0.3)",
    name: "Sage Green",
    description: "Natural and peaceful",
  },
  purple: {
    primary: "#5B21B6",
    primaryLight: "#DDD6FE",
    primaryDark: "#4C1D95",
    onPrimary: "#FFFFFF",
    background: "#FFFFFF",
    cardBackground: "#FFFFFF",
    modalBackground: "#FFFFFF",
    ...HIGH_CONTRAST_SURFACE,
    textPrimary: "#000000",
    textSecondary: "#333333",
    textTertiary: "#666666",
    border: "#000000",
    divider: "#000000",
    success: "#007A3D",
    warning: "#B35900",
    error: "#CC0000",
    info: "#0052CC",
    ...HIGH_CONTRAST_SEMANTIC,
    infoBackground: "#DDD6FE",
    onInfo: "#4C1D95",
    inputBorder: "#000000",
    inputBackground: "#FFFFFF",
    inputPlaceholder: "#666666",
    toggleTrackOn: "#000000",
    toggleTrackOff: "#666666",
    toggleThumb: TOGGLE_THUMB,
    buttonDisabled: "#666666",
    buttonDisabledText: "#333333",
    tabBarActive: "#000000",
    tabBarInactive: "#333333",
    buttonText: "#FFFFFF",
    linkText: "#5B21B6",
    shadow: "rgba(0, 0, 0, 0.3)",
    name: "Purple",
    description: "Creative and vibrant",
  },
  orange: {
    primary: "#CC7A00",
    primaryLight: "#FFE6B3",
    primaryDark: "#995C00",
    onPrimary: "#FFFFFF",
    background: "#FFFFFF",
    cardBackground: "#FFFFFF",
    modalBackground: "#FFFFFF",
    ...HIGH_CONTRAST_SURFACE,
    textPrimary: "#000000",
    textSecondary: "#333333",
    textTertiary: "#666666",
    border: "#000000",
    divider: "#000000",
    success: "#007A3D",
    warning: "#B35900",
    error: "#CC0000",
    info: "#0052CC",
    ...HIGH_CONTRAST_SEMANTIC,
    infoBackground: "#FFE6B3",
    onInfo: "#995C00",
    inputBorder: "#000000",
    inputBackground: "#FFFFFF",
    inputPlaceholder: "#666666",
    toggleTrackOn: "#000000",
    toggleTrackOff: "#666666",
    toggleThumb: TOGGLE_THUMB,
    buttonDisabled: "#666666",
    buttonDisabledText: "#333333",
    tabBarActive: "#000000",
    tabBarInactive: "#333333",
    buttonText: "#FFFFFF",
    linkText: "#CC7A00",
    shadow: "rgba(0, 0, 0, 0.3)",
    name: "Warm Orange",
    description: "Energetic and cheerful",
  },
  pink: {
    primary: "#CC4444",
    primaryLight: "#FFE0E0",
    primaryDark: "#AA3333",
    onPrimary: "#FFFFFF",
    background: "#FFFFFF",
    cardBackground: "#FFFFFF",
    modalBackground: "#FFFFFF",
    ...HIGH_CONTRAST_SURFACE,
    textPrimary: "#000000",
    textSecondary: "#333333",
    textTertiary: "#666666",
    border: "#000000",
    divider: "#000000",
    success: "#007A3D",
    warning: "#B35900",
    error: "#CC0000",
    info: "#0052CC",
    ...HIGH_CONTRAST_SEMANTIC,
    infoBackground: "#FFE0E0",
    onInfo: "#AA3333",
    inputBorder: "#000000",
    inputBackground: "#FFFFFF",
    inputPlaceholder: "#666666",
    toggleTrackOn: "#000000",
    toggleTrackOff: "#666666",
    toggleThumb: TOGGLE_THUMB,
    buttonDisabled: "#666666",
    buttonDisabledText: "#333333",
    tabBarActive: "#000000",
    tabBarInactive: "#333333",
    buttonText: "#FFFFFF",
    linkText: "#CC4444",
    shadow: "rgba(0, 0, 0, 0.3)",
    name: "Coral",
    description: "Warm and vibrant",
  },
  teal: {
    primary: "#6B21A8",
    primaryLight: "#E9D5FF",
    primaryDark: "#581C87",
    onPrimary: "#FFFFFF",
    background: "#FFFFFF",
    cardBackground: "#FFFFFF",
    modalBackground: "#FFFFFF",
    ...HIGH_CONTRAST_SURFACE,
    textPrimary: "#000000",
    textSecondary: "#333333",
    textTertiary: "#666666",
    border: "#000000",
    divider: "#000000",
    success: "#007A3D",
    warning: "#B35900",
    error: "#CC0000",
    info: "#0052CC",
    ...HIGH_CONTRAST_SEMANTIC,
    infoBackground: "#E9D5FF",
    onInfo: "#581C87",
    inputBorder: "#000000",
    inputBackground: "#FFFFFF",
    inputPlaceholder: "#666666",
    toggleTrackOn: "#000000",
    toggleTrackOff: "#666666",
    toggleThumb: TOGGLE_THUMB,
    buttonDisabled: "#666666",
    buttonDisabledText: "#333333",
    tabBarActive: "#000000",
    tabBarInactive: "#333333",
    buttonText: "#FFFFFF",
    linkText: "#6B21A8",
    shadow: "rgba(0, 0, 0, 0.3)",
    name: "Purple",
    description: "Elegant and soothing",
  },
};

// DARK HIGH CONTRAST MODE - Pure black background with maximum contrast
export const DARK_HIGH_CONTRAST_THEMES: Record<ColorTheme, ThemeColors> = {
  blue: {
    primary: "#66B3FF",
    primaryLight: "#1A3050",
    primaryDark: "#99CCFF",
    onPrimary: "#000000",
    background: "#000000",
    cardBackground: "#1A1A1A",
    modalBackground: "#1A1A1A",
    ...DARK_HIGH_CONTRAST_SURFACE,
    textPrimary: "#FFFFFF",
    textSecondary: "#CCCCCC",
    textTertiary: "#999999",
    border: "#FFFFFF",
    divider: "#FFFFFF",
    success: "#66FF99",
    warning: "#FFD666",
    error: "#FF6666",
    info: "#66B3FF",
    ...DARK_HIGH_CONTRAST_SEMANTIC,
    infoBackground: "#1A3050",
    onInfo: "#66B3FF",
    inputBorder: "#FFFFFF",
    inputBackground: "#1A1A1A",
    inputPlaceholder: "#999999",
    toggleTrackOn: "#FFFFFF",
    toggleTrackOff: "#999999",
    toggleThumb: "#000000",
    buttonDisabled: "#999999",
    buttonDisabledText: "#CCCCCC",
    tabBarActive: "#FFFFFF",
    tabBarInactive: "#CCCCCC",
    buttonText: "#000000",
    linkText: "#66B3FF",
    shadow: "rgba(255, 255, 255, 0.15)",
    name: "Ocean Blue",
    description: "Classic and calming",
  },
  sage: {
    primary: "#66DDAA",
    primaryLight: "#1A3A2A",
    primaryDark: "#88EEBB",
    onPrimary: "#000000",
    background: "#000000",
    cardBackground: "#1A1A1A",
    modalBackground: "#1A1A1A",
    ...DARK_HIGH_CONTRAST_SURFACE,
    textPrimary: "#FFFFFF",
    textSecondary: "#CCCCCC",
    textTertiary: "#999999",
    border: "#FFFFFF",
    divider: "#FFFFFF",
    success: "#66FF99",
    warning: "#FFD666",
    error: "#FF6666",
    info: "#66B3FF",
    ...DARK_HIGH_CONTRAST_SEMANTIC,
    infoBackground: "#1A3A2A",
    onInfo: "#66DDAA",
    inputBorder: "#FFFFFF",
    inputBackground: "#1A1A1A",
    inputPlaceholder: "#999999",
    toggleTrackOn: "#FFFFFF",
    toggleTrackOff: "#999999",
    toggleThumb: "#000000",
    buttonDisabled: "#999999",
    buttonDisabledText: "#CCCCCC",
    tabBarActive: "#FFFFFF",
    tabBarInactive: "#CCCCCC",
    buttonText: "#000000",
    linkText: "#66DDAA",
    shadow: "rgba(255, 255, 255, 0.15)",
    name: "Sage Green",
    description: "Natural and peaceful",
  },
  purple: {
    primary: "#B99AFF",
    primaryLight: "#2A1A50",
    primaryDark: "#D4BBFF",
    onPrimary: "#000000",
    background: "#000000",
    cardBackground: "#1A1A1A",
    modalBackground: "#1A1A1A",
    ...DARK_HIGH_CONTRAST_SURFACE,
    textPrimary: "#FFFFFF",
    textSecondary: "#CCCCCC",
    textTertiary: "#999999",
    border: "#FFFFFF",
    divider: "#FFFFFF",
    success: "#66FF99",
    warning: "#FFD666",
    error: "#FF6666",
    info: "#66B3FF",
    ...DARK_HIGH_CONTRAST_SEMANTIC,
    infoBackground: "#2A1A50",
    onInfo: "#B99AFF",
    inputBorder: "#FFFFFF",
    inputBackground: "#1A1A1A",
    inputPlaceholder: "#999999",
    toggleTrackOn: "#FFFFFF",
    toggleTrackOff: "#999999",
    toggleThumb: "#000000",
    buttonDisabled: "#999999",
    buttonDisabledText: "#CCCCCC",
    tabBarActive: "#FFFFFF",
    tabBarInactive: "#CCCCCC",
    buttonText: "#000000",
    linkText: "#B99AFF",
    shadow: "rgba(255, 255, 255, 0.15)",
    name: "Purple",
    description: "Creative and vibrant",
  },
  orange: {
    primary: "#FFCC66",
    primaryLight: "#3A2E10",
    primaryDark: "#FFDD88",
    onPrimary: "#000000",
    background: "#000000",
    cardBackground: "#1A1A1A",
    modalBackground: "#1A1A1A",
    ...DARK_HIGH_CONTRAST_SURFACE,
    textPrimary: "#FFFFFF",
    textSecondary: "#CCCCCC",
    textTertiary: "#999999",
    border: "#FFFFFF",
    divider: "#FFFFFF",
    success: "#66FF99",
    warning: "#FFD666",
    error: "#FF6666",
    info: "#66B3FF",
    ...DARK_HIGH_CONTRAST_SEMANTIC,
    infoBackground: "#3A2E10",
    onInfo: "#FFCC66",
    inputBorder: "#FFFFFF",
    inputBackground: "#1A1A1A",
    inputPlaceholder: "#999999",
    toggleTrackOn: "#FFFFFF",
    toggleTrackOff: "#999999",
    toggleThumb: "#000000",
    buttonDisabled: "#999999",
    buttonDisabledText: "#CCCCCC",
    tabBarActive: "#FFFFFF",
    tabBarInactive: "#CCCCCC",
    buttonText: "#000000",
    linkText: "#FFCC66",
    shadow: "rgba(255, 255, 255, 0.15)",
    name: "Warm Orange",
    description: "Energetic and cheerful",
  },
  pink: {
    primary: "#FF9999",
    primaryLight: "#3A1A1A",
    primaryDark: "#FFBBBB",
    onPrimary: "#000000",
    background: "#000000",
    cardBackground: "#1A1A1A",
    modalBackground: "#1A1A1A",
    ...DARK_HIGH_CONTRAST_SURFACE,
    textPrimary: "#FFFFFF",
    textSecondary: "#CCCCCC",
    textTertiary: "#999999",
    border: "#FFFFFF",
    divider: "#FFFFFF",
    success: "#66FF99",
    warning: "#FFD666",
    error: "#FF6666",
    info: "#66B3FF",
    ...DARK_HIGH_CONTRAST_SEMANTIC,
    infoBackground: "#3A1A1A",
    onInfo: "#FF9999",
    inputBorder: "#FFFFFF",
    inputBackground: "#1A1A1A",
    inputPlaceholder: "#999999",
    toggleTrackOn: "#FFFFFF",
    toggleTrackOff: "#999999",
    toggleThumb: "#000000",
    buttonDisabled: "#999999",
    buttonDisabledText: "#CCCCCC",
    tabBarActive: "#FFFFFF",
    tabBarInactive: "#CCCCCC",
    buttonText: "#000000",
    linkText: "#FF9999",
    shadow: "rgba(255, 255, 255, 0.15)",
    name: "Coral",
    description: "Warm and vibrant",
  },
  teal: {
    primary: "#BB88FF",
    primaryLight: "#2A1A40",
    primaryDark: "#DDAAFF",
    onPrimary: "#000000",
    background: "#000000",
    cardBackground: "#1A1A1A",
    modalBackground: "#1A1A1A",
    ...DARK_HIGH_CONTRAST_SURFACE,
    textPrimary: "#FFFFFF",
    textSecondary: "#CCCCCC",
    textTertiary: "#999999",
    border: "#FFFFFF",
    divider: "#FFFFFF",
    success: "#66FF99",
    warning: "#FFD666",
    error: "#FF6666",
    info: "#66B3FF",
    ...DARK_HIGH_CONTRAST_SEMANTIC,
    infoBackground: "#2A1A40",
    onInfo: "#BB88FF",
    inputBorder: "#FFFFFF",
    inputBackground: "#1A1A1A",
    inputPlaceholder: "#999999",
    toggleTrackOn: "#FFFFFF",
    toggleTrackOff: "#999999",
    toggleThumb: "#000000",
    buttonDisabled: "#999999",
    buttonDisabledText: "#CCCCCC",
    tabBarActive: "#FFFFFF",
    tabBarInactive: "#CCCCCC",
    buttonText: "#000000",
    linkText: "#BB88FF",
    shadow: "rgba(255, 255, 255, 0.15)",
    name: "Purple",
    description: "Elegant and soothing",
  },
};

// COLOR-BLIND FRIENDLY PALETTES (using blue/orange/gray palette)
export const COLORBLIND_THEMES: Record<ColorTheme, ThemeColors> = {
  blue: {
    primary: "#0077BB",
    primaryLight: "#D4E9F7",
    primaryDark: "#004C77",
    onPrimary: "#FFFFFF",
    background: "#F5F9FF",
    cardBackground: "#FFFFFF",
    modalBackground: "#FFFFFF",
    ...LIGHT_SURFACE,
    textPrimary: "#1A1A1A",
    textSecondary: "#525252",
    textTertiary: "#888888",
    border: "#DDDDDD",
    divider: "#E5E5E5",
    success: "#0077BB",
    warning: "#EE7733",
    error: "#CC3311",
    info: "#0077BB",
    ...COLORBLIND_SEMANTIC,
    infoBackground: "#D4E9F7",
    onInfo: "#004C77",
    inputBorder: INPUT_BORDER_LIGHT,
    inputBackground: "#FFFFFF",
    inputPlaceholder: "#888888",
    toggleTrackOn: "#0077BB",
    toggleTrackOff: TOGGLE_TRACK_OFF_LIGHT,
    toggleThumb: TOGGLE_THUMB,
    buttonDisabled: BUTTON_DISABLED_LIGHT,
    buttonDisabledText: BUTTON_DISABLED_TEXT_LIGHT,
    tabBarActive: "#0077BB",
    tabBarInactive: TAB_BAR_INACTIVE_LIGHT,
    buttonText: "#FFFFFF",
    linkText: "#0077BB",
    shadow: "rgba(0, 0, 0, 0.1)",
    name: "Ocean Blue",
    description: "Classic and calming",
  },
  sage: {
    primary: "#0077BB",
    primaryLight: "#D4E9F7",
    primaryDark: "#004C77",
    onPrimary: "#FFFFFF",
    background: "#F5F9F5",
    cardBackground: "#FFFFFF",
    modalBackground: "#FFFFFF",
    ...LIGHT_SURFACE,
    textPrimary: "#1A1A1A",
    textSecondary: "#525252",
    textTertiary: "#888888",
    border: "#DDDDDD",
    divider: "#E5E5E5",
    success: "#0077BB",
    warning: "#EE7733",
    error: "#CC3311",
    info: "#0077BB",
    ...COLORBLIND_SEMANTIC,
    infoBackground: "#D4E9F7",
    onInfo: "#004C77",
    inputBorder: INPUT_BORDER_LIGHT,
    inputBackground: "#FFFFFF",
    inputPlaceholder: "#888888",
    toggleTrackOn: "#0077BB",
    toggleTrackOff: TOGGLE_TRACK_OFF_LIGHT,
    toggleThumb: TOGGLE_THUMB,
    buttonDisabled: BUTTON_DISABLED_LIGHT,
    buttonDisabledText: BUTTON_DISABLED_TEXT_LIGHT,
    tabBarActive: "#0077BB",
    tabBarInactive: TAB_BAR_INACTIVE_LIGHT,
    buttonText: "#FFFFFF",
    linkText: "#0077BB",
    shadow: "rgba(0, 0, 0, 0.1)",
    name: "Sage Green",
    description: "Natural and peaceful",
  },
  purple: {
    primary: "#0077BB",
    primaryLight: "#D4E9F7",
    primaryDark: "#004C77",
    onPrimary: "#FFFFFF",
    background: "#F8F5FF",
    cardBackground: "#FFFFFF",
    modalBackground: "#FFFFFF",
    ...LIGHT_SURFACE,
    textPrimary: "#1A1A1A",
    textSecondary: "#525252",
    textTertiary: "#888888",
    border: "#DDDDDD",
    divider: "#E5E5E5",
    success: "#0077BB",
    warning: "#EE7733",
    error: "#CC3311",
    info: "#0077BB",
    ...COLORBLIND_SEMANTIC,
    infoBackground: "#D4E9F7",
    onInfo: "#004C77",
    inputBorder: INPUT_BORDER_LIGHT,
    inputBackground: "#FFFFFF",
    inputPlaceholder: "#888888",
    toggleTrackOn: "#0077BB",
    toggleTrackOff: TOGGLE_TRACK_OFF_LIGHT,
    toggleThumb: TOGGLE_THUMB,
    buttonDisabled: BUTTON_DISABLED_LIGHT,
    buttonDisabledText: BUTTON_DISABLED_TEXT_LIGHT,
    tabBarActive: "#0077BB",
    tabBarInactive: TAB_BAR_INACTIVE_LIGHT,
    buttonText: "#FFFFFF",
    linkText: "#0077BB",
    shadow: "rgba(0, 0, 0, 0.1)",
    name: "Purple",
    description: "Creative and vibrant",
  },
  orange: {
    primary: "#EE7733",
    primaryLight: "#FFECD4",
    primaryDark: "#BB4411",
    onPrimary: "#FFFFFF",
    background: "#FFF9ED",
    cardBackground: "#FFFFFF",
    modalBackground: "#FFFFFF",
    ...LIGHT_SURFACE,
    textPrimary: "#1A1A1A",
    textSecondary: "#525252",
    textTertiary: "#888888",
    border: "#DDDDDD",
    divider: "#E5E5E5",
    success: "#0077BB",
    warning: "#EE7733",
    error: "#CC3311",
    info: "#0077BB",
    ...COLORBLIND_SEMANTIC,
    infoBackground: "#FFECD4",
    onInfo: "#BB4411",
    inputBorder: INPUT_BORDER_LIGHT,
    inputBackground: "#FFFFFF",
    inputPlaceholder: "#888888",
    toggleTrackOn: "#EE7733",
    toggleTrackOff: TOGGLE_TRACK_OFF_LIGHT,
    toggleThumb: TOGGLE_THUMB,
    buttonDisabled: BUTTON_DISABLED_LIGHT,
    buttonDisabledText: BUTTON_DISABLED_TEXT_LIGHT,
    tabBarActive: "#EE7733",
    tabBarInactive: TAB_BAR_INACTIVE_LIGHT,
    buttonText: "#FFFFFF",
    linkText: "#EE7733",
    shadow: "rgba(0, 0, 0, 0.1)",
    name: "Warm Orange",
    description: "Energetic and cheerful",
  },
  pink: {
    primary: "#EE7733",
    primaryLight: "#FFECD4",
    primaryDark: "#BB4411",
    onPrimary: "#FFFFFF",
    background: "#FFF5F5",
    cardBackground: "#FFFFFF",
    modalBackground: "#FFFFFF",
    ...LIGHT_SURFACE,
    textPrimary: "#1A1A1A",
    textSecondary: "#525252",
    textTertiary: "#888888",
    border: "#DDDDDD",
    divider: "#E5E5E5",
    success: "#0077BB",
    warning: "#EE7733",
    error: "#CC3311",
    info: "#0077BB",
    ...COLORBLIND_SEMANTIC,
    infoBackground: "#FFECD4",
    onInfo: "#BB4411",
    inputBorder: INPUT_BORDER_LIGHT,
    inputBackground: "#FFFFFF",
    inputPlaceholder: "#888888",
    toggleTrackOn: "#EE7733",
    toggleTrackOff: TOGGLE_TRACK_OFF_LIGHT,
    toggleThumb: TOGGLE_THUMB,
    buttonDisabled: BUTTON_DISABLED_LIGHT,
    buttonDisabledText: BUTTON_DISABLED_TEXT_LIGHT,
    tabBarActive: "#EE7733",
    tabBarInactive: TAB_BAR_INACTIVE_LIGHT,
    buttonText: "#FFFFFF",
    linkText: "#EE7733",
    shadow: "rgba(0, 0, 0, 0.1)",
    name: "Coral",
    description: "Warm and vibrant",
  },
  teal: {
    primary: "#7C3AED",
    primaryLight: "#DDD6FE",
    primaryDark: "#5B21B6",
    onPrimary: "#FFFFFF",
    background: "#F5F3FF",
    cardBackground: "#FFFFFF",
    modalBackground: "#FFFFFF",
    ...LIGHT_SURFACE,
    textPrimary: "#1A1A1A",
    textSecondary: "#525252",
    textTertiary: "#888888",
    border: "#DDDDDD",
    divider: "#E5E5E5",
    success: "#0077BB",
    warning: "#EE7733",
    error: "#CC3311",
    info: "#0077BB",
    ...COLORBLIND_SEMANTIC,
    infoBackground: "#DDD6FE",
    onInfo: "#5B21B6",
    inputBorder: INPUT_BORDER_LIGHT,
    inputBackground: "#FFFFFF",
    inputPlaceholder: "#888888",
    toggleTrackOn: "#7C3AED",
    toggleTrackOff: TOGGLE_TRACK_OFF_LIGHT,
    toggleThumb: TOGGLE_THUMB,
    buttonDisabled: BUTTON_DISABLED_LIGHT,
    buttonDisabledText: BUTTON_DISABLED_TEXT_LIGHT,
    tabBarActive: "#7C3AED",
    tabBarInactive: TAB_BAR_INACTIVE_LIGHT,
    buttonText: "#FFFFFF",
    linkText: "#7C3AED",
    shadow: "rgba(0, 0, 0, 0.1)",
    name: "Purple",
    description: "Elegant and soothing",
  },
};

// DARK COLOR-BLIND FRIENDLY PALETTES (blue/orange safe on dark backgrounds)
export const DARK_COLORBLIND_THEMES: Record<ColorTheme, ThemeColors> = {
  blue: {
    primary: "#66BBEE",
    primaryLight: "#1A3050",
    primaryDark: "#88CCFF",
    onPrimary: "#1A1A1A",
    background: "#2B2B2B",
    cardBackground: "#363636",
    modalBackground: "#3D3D3D",
    ...DARK_COLORBLIND_SURFACE,
    textPrimary: "#E8E8E8",
    textSecondary: "#B3B3B3",
    textTertiary: "#808080",
    border: "#4A4A4A",
    divider: "#3D3D3D",
    success: "#66BBEE",
    warning: "#FFAA66",
    error: "#FF8866",
    info: "#66BBEE",
    ...DARK_COLORBLIND_SEMANTIC,
    infoBackground: "#1A3050",
    onInfo: "#66BBEE",
    inputBorder: INPUT_BORDER_DARK,
    inputBackground: "#3D3D3D",
    inputPlaceholder: "#808080",
    toggleTrackOn: "#66BBEE",
    toggleTrackOff: TOGGLE_TRACK_OFF_DARK,
    toggleThumb: TOGGLE_THUMB,
    buttonDisabled: BUTTON_DISABLED_DARK,
    buttonDisabledText: BUTTON_DISABLED_TEXT_DARK,
    tabBarActive: "#66BBEE",
    tabBarInactive: TAB_BAR_INACTIVE_DARK,
    buttonText: "#1A1A1A",
    linkText: "#66BBEE",
    shadow: "rgba(0, 0, 0, 0.4)",
    name: "Ocean Blue",
    description: "Classic and calming",
  },
  sage: {
    primary: "#66BBEE",
    primaryLight: "#1A3050",
    primaryDark: "#88CCFF",
    onPrimary: "#1A1A1A",
    background: "#2B2B2B",
    cardBackground: "#363636",
    modalBackground: "#3D3D3D",
    ...DARK_COLORBLIND_SURFACE,
    textPrimary: "#E8E8E8",
    textSecondary: "#B3B3B3",
    textTertiary: "#808080",
    border: "#4A4A4A",
    divider: "#3D3D3D",
    success: "#66BBEE",
    warning: "#FFAA66",
    error: "#FF8866",
    info: "#66BBEE",
    ...DARK_COLORBLIND_SEMANTIC,
    infoBackground: "#1A3050",
    onInfo: "#66BBEE",
    inputBorder: INPUT_BORDER_DARK,
    inputBackground: "#3D3D3D",
    inputPlaceholder: "#808080",
    toggleTrackOn: "#66BBEE",
    toggleTrackOff: TOGGLE_TRACK_OFF_DARK,
    toggleThumb: TOGGLE_THUMB,
    buttonDisabled: BUTTON_DISABLED_DARK,
    buttonDisabledText: BUTTON_DISABLED_TEXT_DARK,
    tabBarActive: "#66BBEE",
    tabBarInactive: TAB_BAR_INACTIVE_DARK,
    buttonText: "#1A1A1A",
    linkText: "#66BBEE",
    shadow: "rgba(0, 0, 0, 0.4)",
    name: "Sage Green",
    description: "Natural and peaceful",
  },
  purple: {
    primary: "#66BBEE",
    primaryLight: "#1A3050",
    primaryDark: "#88CCFF",
    onPrimary: "#1A1A1A",
    background: "#2B2B2B",
    cardBackground: "#363636",
    modalBackground: "#3D3D3D",
    ...DARK_COLORBLIND_SURFACE,
    textPrimary: "#E8E8E8",
    textSecondary: "#B3B3B3",
    textTertiary: "#808080",
    border: "#4A4A4A",
    divider: "#3D3D3D",
    success: "#66BBEE",
    warning: "#FFAA66",
    error: "#FF8866",
    info: "#66BBEE",
    ...DARK_COLORBLIND_SEMANTIC,
    infoBackground: "#1A3050",
    onInfo: "#66BBEE",
    inputBorder: INPUT_BORDER_DARK,
    inputBackground: "#3D3D3D",
    inputPlaceholder: "#808080",
    toggleTrackOn: "#66BBEE",
    toggleTrackOff: TOGGLE_TRACK_OFF_DARK,
    toggleThumb: TOGGLE_THUMB,
    buttonDisabled: BUTTON_DISABLED_DARK,
    buttonDisabledText: BUTTON_DISABLED_TEXT_DARK,
    tabBarActive: "#66BBEE",
    tabBarInactive: TAB_BAR_INACTIVE_DARK,
    buttonText: "#1A1A1A",
    linkText: "#66BBEE",
    shadow: "rgba(0, 0, 0, 0.4)",
    name: "Purple",
    description: "Creative and vibrant",
  },
  orange: {
    primary: "#FFAA66",
    primaryLight: "#3A2510",
    primaryDark: "#FFCC88",
    onPrimary: "#1A1A1A",
    background: "#2B2B2B",
    cardBackground: "#363636",
    modalBackground: "#3D3D3D",
    ...DARK_COLORBLIND_SURFACE,
    textPrimary: "#E8E8E8",
    textSecondary: "#B3B3B3",
    textTertiary: "#808080",
    border: "#4A4A4A",
    divider: "#3D3D3D",
    success: "#66BBEE",
    warning: "#FFAA66",
    error: "#FF8866",
    info: "#66BBEE",
    ...DARK_COLORBLIND_SEMANTIC,
    infoBackground: "#3A2510",
    onInfo: "#FFAA66",
    inputBorder: INPUT_BORDER_DARK,
    inputBackground: "#3D3D3D",
    inputPlaceholder: "#808080",
    toggleTrackOn: "#FFAA66",
    toggleTrackOff: TOGGLE_TRACK_OFF_DARK,
    toggleThumb: TOGGLE_THUMB,
    buttonDisabled: BUTTON_DISABLED_DARK,
    buttonDisabledText: BUTTON_DISABLED_TEXT_DARK,
    tabBarActive: "#FFAA66",
    tabBarInactive: TAB_BAR_INACTIVE_DARK,
    buttonText: "#1A1A1A",
    linkText: "#FFAA66",
    shadow: "rgba(0, 0, 0, 0.4)",
    name: "Warm Orange",
    description: "Energetic and cheerful",
  },
  pink: {
    primary: "#FFAA66",
    primaryLight: "#3A2510",
    primaryDark: "#FFCC88",
    onPrimary: "#1A1A1A",
    background: "#2B2B2B",
    cardBackground: "#363636",
    modalBackground: "#3D3D3D",
    ...DARK_COLORBLIND_SURFACE,
    textPrimary: "#E8E8E8",
    textSecondary: "#B3B3B3",
    textTertiary: "#808080",
    border: "#4A4A4A",
    divider: "#3D3D3D",
    success: "#66BBEE",
    warning: "#FFAA66",
    error: "#FF8866",
    info: "#66BBEE",
    ...DARK_COLORBLIND_SEMANTIC,
    infoBackground: "#3A2510",
    onInfo: "#FFAA66",
    inputBorder: INPUT_BORDER_DARK,
    inputBackground: "#3D3D3D",
    inputPlaceholder: "#808080",
    toggleTrackOn: "#FFAA66",
    toggleTrackOff: TOGGLE_TRACK_OFF_DARK,
    toggleThumb: TOGGLE_THUMB,
    buttonDisabled: BUTTON_DISABLED_DARK,
    buttonDisabledText: BUTTON_DISABLED_TEXT_DARK,
    tabBarActive: "#FFAA66",
    tabBarInactive: TAB_BAR_INACTIVE_DARK,
    buttonText: "#1A1A1A",
    linkText: "#FFAA66",
    shadow: "rgba(0, 0, 0, 0.4)",
    name: "Coral",
    description: "Warm and vibrant",
  },
  teal: {
    primary: "#BB88FF",
    primaryLight: "#2A1A40",
    primaryDark: "#DDAAFF",
    onPrimary: "#1A1A1A",
    background: "#2B2B2B",
    cardBackground: "#363636",
    modalBackground: "#3D3D3D",
    ...DARK_COLORBLIND_SURFACE,
    textPrimary: "#E8E8E8",
    textSecondary: "#B3B3B3",
    textTertiary: "#808080",
    border: "#4A4A4A",
    divider: "#3D3D3D",
    success: "#66BBEE",
    warning: "#FFAA66",
    error: "#FF8866",
    info: "#66BBEE",
    ...DARK_COLORBLIND_SEMANTIC,
    infoBackground: "#2A1A40",
    onInfo: "#BB88FF",
    inputBorder: INPUT_BORDER_DARK,
    inputBackground: "#3D3D3D",
    inputPlaceholder: "#808080",
    toggleTrackOn: "#BB88FF",
    toggleTrackOff: TOGGLE_TRACK_OFF_DARK,
    toggleThumb: TOGGLE_THUMB,
    buttonDisabled: BUTTON_DISABLED_DARK,
    buttonDisabledText: BUTTON_DISABLED_TEXT_DARK,
    tabBarActive: "#BB88FF",
    tabBarInactive: TAB_BAR_INACTIVE_DARK,
    buttonText: "#1A1A1A",
    linkText: "#BB88FF",
    shadow: "rgba(0, 0, 0, 0.4)",
    name: "Purple",
    description: "Elegant and soothing",
  },
};

export function getThemeColors(
  theme: ColorTheme,
  appearanceMode: AppearanceMode = "light",
  accessibilityMode: AccessibilityMode = "default"
): ThemeColors {
  // Determine if dark mode is active
  let isDark = false;
  if (appearanceMode === "dark") {
    isDark = true;
  } else if (appearanceMode === "system") {
    const systemColorScheme = Appearance.getColorScheme();
    isDark = systemColorScheme === "dark";
  }

  // Accessibility modes respect the user's light/dark preference
  if (accessibilityMode === "high-contrast") {
    return isDark ? DARK_HIGH_CONTRAST_THEMES[theme] : HIGH_CONTRAST_THEMES[theme];
  }

  if (accessibilityMode === "color-blind-friendly") {
    return isDark ? DARK_COLORBLIND_THEMES[theme] : COLORBLIND_THEMES[theme];
  }

  if (isDark) {
    return DARK_COLOR_THEMES[theme];
  }

  return COLOR_THEMES[theme];
}
