// Common insurance providers for autocomplete (200+ providers)
export const commonInsuranceProviders = [
  // Major National Insurers (30)
  "UnitedHealthcare",
  "Blue Cross Blue Shield",
  "Anthem Blue Cross",
  "Anthem Blue Cross Blue Shield",
  "Aetna",
  "Cigna",
  "Humana",
  "Kaiser Permanente",
  "Centene",
  "Molina Healthcare",
  "WellCare",
  "Health Net",
  "Ambetter",
  "Oscar Health",
  "Bright Health",
  "Friday Health Plans",
  "Devoted Health",
  "Clover Health",
  "Alignment Healthcare",
  "CareSource",
  "HealthFirst",
  "AmeriHealth",
  "Independence Blue Cross",
  "Highmark",
  "Premera Blue Cross",
  "Regence",
  "Cambia Health Solutions",
  "SCAN Health Plan",
  "WellPoint",
  "Elevance Health",

  // Medicare & Medicaid Plans (25)
  "Medicare",
  "Medicaid",
  "Medicare Advantage",
  "UnitedHealthcare Medicare",
  "Humana Medicare",
  "Aetna Medicare",
  "Cigna Medicare",
  "Kaiser Permanente Medicare",
  "Blue Cross Medicare",
  "WellCare Medicare",
  "Devoted Health Medicare",
  "SCAN Medicare",
  "Alignment Medicare",
  "Clover Medicare",
  "Medicare Part A",
  "Medicare Part B",
  "Medicare Part D",
  "Medigap",
  "Medicare Supplement",
  "Medicaid Managed Care",
  "Dual Eligible Special Needs Plan",
  "Medicare-Medicaid Plan",
  "PACE (Program of All-Inclusive Care)",
  "QMB (Qualified Medicare Beneficiary)",
  "SLMB (Specified Low-Income Medicare Beneficiary)",

  // Regional Blues Plans (50)
  "Anthem California",
  "Anthem Colorado",
  "Anthem Connecticut",
  "Anthem Georgia",
  "Anthem Indiana",
  "Anthem Kentucky",
  "Anthem Maine",
  "Anthem Missouri",
  "Anthem Nevada",
  "Anthem New Hampshire",
  "Anthem New York",
  "Anthem Ohio",
  "Anthem Virginia",
  "Anthem Wisconsin",
  "Blue Cross Blue Shield Alabama",
  "Blue Cross Blue Shield Arizona",
  "Blue Cross Blue Shield Arkansas",
  "Blue Cross Blue Shield Delaware",
  "Blue Cross Blue Shield Florida",
  "Blue Cross Blue Shield Georgia",
  "Blue Cross Blue Shield Idaho",
  "Blue Cross Blue Shield Illinois",
  "Blue Cross Blue Shield Kansas",
  "Blue Cross Blue Shield Louisiana",
  "Blue Cross Blue Shield Michigan",
  "Blue Cross Blue Shield Minnesota",
  "Blue Cross Blue Shield Mississippi",
  "Blue Cross Blue Shield Montana",
  "Blue Cross Blue Shield Nebraska",
  "Blue Cross Blue Shield New Mexico",
  "Blue Cross Blue Shield North Carolina",
  "Blue Cross Blue Shield North Dakota",
  "Blue Cross Blue Shield Oklahoma",
  "Blue Cross Blue Shield Rhode Island",
  "Blue Cross Blue Shield South Carolina",
  "Blue Cross Blue Shield Tennessee",
  "Blue Cross Blue Shield Texas",
  "Blue Cross Blue Shield Vermont",
  "Blue Cross Blue Shield Wyoming",
  "Blue Shield California",
  "CareFirst BlueCross BlueShield",
  "Empire BlueCross BlueShield",
  "Excellus BlueCross BlueShield",
  "Florida Blue",
  "Hawaii Medical Service Association",
  "Horizon Blue Cross Blue Shield",
  "Regence BlueCross BlueShield",
  "Wellmark Blue Cross Blue Shield",

  // Other Major Commercial Plans (40)
  "Aetna Better Health",
  "Aetna Medicaid",
  "Cigna HealthSpring",
  "Cigna LocalPlus",
  "UnitedHealthcare Community Plan",
  "UnitedHealthcare Oxford",
  "Humana Gold Plus",
  "Humana Walmart",
  "Kaiser Foundation Health Plan",
  "GEHA",
  "TriCare",
  "TRICARE Prime",
  "TRICARE Select",
  "TRICARE For Life",
  "ChampVA",
  "VA Health Care",
  "Veterans Affairs",
  "Fidelis Care",
  "MetroPlus Health",
  "EmblemHealth",
  "GHI",
  "HIP Health Plan",
  "Affinity Health Plan",
  "MVP Health Care",
  "CDPHP",
  "Tufts Health Plan",
  "Harvard Pilgrim",
  "Fallon Health",
  "AllWays Health Partners",
  "Point32Health",
  "Blue Care Network",
  "Priority Health",
  "HAP (Health Alliance Plan)",
  "Meridian Health Plan",
  "McLaren Health Plan",
  "HealthPartners",
  "Medica",
  "PreferredOne",
  "UCare",
  "Hennepin Health",

  // West Coast Plans (20)
  "Blue Shield of California",
  "Health Net California",
  "LA Care",
  "Medi-Cal",
  "CalOptima",
  "Inland Empire Health Plan",
  "Molina Healthcare California",
  "Sharp Health Plan",
  "Western Health Advantage",
  "Chinese Community Health Plan",
  "Providence Health Plan",
  "PacificSource",
  "Moda Health",
  "Coordinated Care",
  "Trillium",
  "CareOregon",
  "Lifewise",
  "Community Health Plan of Washington",
  "Coordinated Care of Washington",
  "BridgeSpan Health",

  // Employer & Other Plans (15)
  "FEHB (Federal Employee Health Benefits)",
  "PEBB (Public Employees Benefits Board)",
  "SEBB (School Employees Benefits Board)",
  "Railroad Medicare",
  "USAA Health",
  "NALC Health Benefit Plan",
  "APWU Health Plan",
  "MHBP (Mail Handlers Benefit Plan)",
  "SAMBA (Special Agents Mutual Benefit Association)",
  "Foreign Service Benefit Plan",
  "United Concordia",
  "Delta Dental",
  "MetLife Dental",
  "Guardian",
  "Principal Financial",

  // Marketplace & ACA Plans (10)
  "Healthcare.gov Plan",
  "Covered California",
  "NY State of Health",
  "Maryland Health Connection",
  "Massachusetts Health Connector",
  "Connect for Health Colorado",
  "MNsure",
  "Washington Healthplanfinder",
  "Pennie (Pennsylvania)",
  "BeWellNM",

  // Vision Plans (10)
  "VSP Vision Care",
  "EyeMed",
  "Davis Vision",
  "Superior Vision",
  "Avesis",
  "Spectera",
  "United Healthcare Vision",
  "Aetna Vision",
  "Humana Vision",
  "Blue View Vision",
].sort();
