// Common medication names for autocomplete (500+ medications)
export const commonMedications = [
  // Cardiovascular (50)
  "Aspirin",
  "Lisinopril",
  "Atorvastatin",
  "Amlodipine",
  "Metoprolol",
  "Losartan",
  "Simvastatin",
  "Furosemide",
  "Warfarin",
  "Clopidogrel",
  "Carvedilol",
  "Hydrochlorothiazide",
  "Valsartan",
  "Diltiazem",
  "Pravastatin",
  "Rosuvastatin",
  "Apixaban",
  "Rivaroxaban",
  "Digoxin",
  "Spironolactone",
  "Enalapril",
  "Ramipril",
  "Bisoprolol",
  "Nebivolol",
  "Telmisartan",
  "Irbesartan",
  "Candesartan",
  "Ezetimibe",
  "Fenofibrate",
  "Gemfibrozil",
  "Propranolol",
  "Atenolol",
  "Labetalol",
  "Acebutolol",
  "Pindolol",
  "Nadolol",
  "Sotalol",
  "Verapamil",
  "Nifedipine",
  "Felodipine",
  "Isosorbide",
  "Nitroglycerin",
  "Hydralazine",
  "Clonidine",
  "Methyldopa",
  "Doxazosin",
  "Prazosin",
  "Terazosin",
  "Lovastatin",
  "Fluvastatin",

  // Diabetes (30)
  "Metformin",
  "Glipizide",
  "Glyburide",
  "Insulin",
  "Insulin Glargine",
  "Insulin Lispro",
  "Januvia",
  "Jardiance",
  "Ozempic",
  "Trulicity",
  "Victoza",
  "Farxiga",
  "Invokana",
  "Actos",
  "Glucophage",
  "Sitagliptin",
  "Empagliflozin",
  "Semaglutide",
  "Dulaglutide",
  "Liraglutide",
  "Dapagliflozin",
  "Canagliflozin",
  "Pioglitazone",
  "Rosiglitazone",
  "Repaglinide",
  "Nateglinide",
  "Glimepiride",
  "Insulin Aspart",
  "Insulin Detemir",
  "Insulin Degludec",

  // Thyroid (5)
  "Levothyroxine",
  "Synthroid",
  "Armour Thyroid",
  "Cytomel",
  "Liothyronine",

  // Gastrointestinal (25)
  "Omeprazole",
  "Pantoprazole",
  "Esomeprazole",
  "Lansoprazole",
  "Famotidine",
  "Ranitidine",
  "Sucralfate",
  "Dicyclomine",
  "Mesalamine",
  "Loperamide",
  "Polyethylene Glycol",
  "Docusate",
  "Rabeprazole",
  "Dexlansoprazole",
  "Cimetidine",
  "Nizatidine",
  "Metoclopramide",
  "Ondansetron",
  "Promethazine",
  "Hyoscyamine",
  "Bismuth Subsalicylate",
  "Psyllium",
  "Methylcellulose",
  "Sennosides",
  "Bisacodyl",

  // Respiratory (25)
  "Albuterol",
  "Fluticasone",
  "Montelukast",
  "Budesonide",
  "Tiotropium",
  "Symbicort",
  "Advair",
  "Spiriva",
  "Salmeterol",
  "Ipratropium",
  "Dulera",
  "Breo Ellipta",
  "Combivent",
  "Pulmicort",
  "Ventolin",
  "Formoterol",
  "Mometasone",
  "Beclomethasone",
  "Ciclesonide",
  "Zafirlukast",
  "Zileuton",
  "Theophylline",
  "Roflumilast",
  "Cromolyn",
  "Nedocromil",

  // Pain & Inflammation (35)
  "Acetaminophen",
  "Ibuprofen",
  "Naproxen",
  "Tramadol",
  "Gabapentin",
  "Prednisone",
  "Meloxicam",
  "Celecoxib",
  "Diclofenac",
  "Cyclobenzaprine",
  "Methocarbamol",
  "Tizanidine",
  "Baclofen",
  "Hydrocodone",
  "Oxycodone",
  "Morphine",
  "Indomethacin",
  "Ketorolac",
  "Pregabalin",
  "Duloxetine",
  "Amitriptyline",
  "Nortriptyline",
  "Codeine",
  "Fentanyl",
  "Buprenorphine",
  "Tapentadol",
  "Etodolac",
  "Nabumetone",
  "Piroxicam",
  "Sulindac",
  "Cortisone",
  "Hydrocortisone",
  "Methylprednisolone",
  "Dexamethasone",
  "Triamcinolone",

  // Mental Health & Sleep (40)
  "Sertraline",
  "Escitalopram",
  "Citalopram",
  "Fluoxetine",
  "Paroxetine",
  "Duloxetine",
  "Venlafaxine",
  "Bupropion",
  "Trazodone",
  "Mirtazapine",
  "Buspirone",
  "Lorazepam",
  "Alprazolam",
  "Clonazepam",
  "Zolpidem",
  "Quetiapine",
  "Aripiprazole",
  "Risperidone",
  "Olanzapine",
  "Hydroxyzine",
  "Desvenlafaxine",
  "Levomilnacipran",
  "Vilazodone",
  "Vortioxetine",
  "Eszopiclone",
  "Zaleplon",
  "Ramelteon",
  "Suvorexant",
  "Lemborexant",
  "Doxepin",
  "Temazepam",
  "Diazepam",
  "Oxazepam",
  "Chlordiazepoxide",
  "Lithium",
  "Lamotrigine",
  "Valproic Acid",
  "Ziprasidone",
  "Paliperidone",
  "Lurasidone",

  // Antibiotics (25)
  "Amoxicillin",
  "Azithromycin",
  "Ciprofloxacin",
  "Doxycycline",
  "Cephalexin",
  "Levofloxacin",
  "Trimethoprim-Sulfamethoxazole",
  "Clindamycin",
  "Metronidazole",
  "Penicillin",
  "Amoxicillin-Clavulanate",
  "Augmentin",
  "Cefdinir",
  "Cefuroxime",
  "Cefprozil",
  "Clarithromycin",
  "Erythromycin",
  "Moxifloxacin",
  "Nitrofurantoin",
  "Sulfamethoxazole",
  "Vancomycin",
  "Linezolid",
  "Rifampin",
  "Isoniazid",
  "Fluconazole",

  // Neurological (25)
  "Donepezil",
  "Memantine",
  "Levodopa",
  "Carbidopa-Levodopa",
  "Pramipexole",
  "Ropinirole",
  "Topiramate",
  "Lamotrigine",
  "Carbamazepine",
  "Phenytoin",
  "Rivastigmine",
  "Galantamine",
  "Selegiline",
  "Rasagiline",
  "Entacapone",
  "Amantadine",
  "Levetiracetam",
  "Oxcarbazepine",
  "Valproate",
  "Zonisamide",
  "Lacosamide",
  "Phenobarbital",
  "Primidone",
  "Vigabatrin",
  "Tiagabine",

  // Urological (15)
  "Tamsulosin",
  "Finasteride",
  "Dutasteride",
  "Oxybutynin",
  "Tolterodine",
  "Solifenacin",
  "Mirabegron",
  "Sildenafil",
  "Tadalafil",
  "Vardenafil",
  "Alfuzosin",
  "Doxazosin",
  "Darifenacin",
  "Trospium",
  "Fesoterodine",

  // Osteoporosis & Bone Health (10)
  "Alendronate",
  "Risedronate",
  "Ibandronate",
  "Denosumab",
  "Raloxifene",
  "Zoledronic Acid",
  "Teriparatide",
  "Abaloparatide",
  "Romosozumab",
  "Calcitonin",

  // Eye & Ear (20)
  "Latanoprost",
  "Timolol",
  "Brimonidine",
  "Prednisolone Eye Drops",
  "Ciprofloxacin Eye Drops",
  "Travoprost",
  "Bimatoprost",
  "Dorzolamide",
  "Brinzolamide",
  "Apraclonidine",
  "Cyclopentolate",
  "Tropicamide",
  "Atropine Eye Drops",
  "Ketorolac Eye Drops",
  "Ofloxacin Eye Drops",
  "Tobramycin Eye Drops",
  "Gentamicin Eye Drops",
  "Erythromycin Ointment",
  "Artificial Tears",
  "Cyclosporine Eye Drops",

  // Allergy & Antihistamines (15)
  "Cetirizine",
  "Loratadine",
  "Fexofenadine",
  "Diphenhydramine",
  "Promethazine",
  "Meclizine",
  "Chlorpheniramine",
  "Pseudoephedrine",
  "Desloratadine",
  "Levocetirizine",
  "Azelastine",
  "Olopatadine",
  "Phenylephrine",
  "Guaifenesin",
  "Dextromethorphan",

  // Vitamins & Supplements (30)
  "Vitamin D",
  "Vitamin D3",
  "Calcium",
  "Calcium Citrate",
  "Multivitamin",
  "Fish Oil",
  "Omega-3",
  "CoQ10",
  "Magnesium",
  "Vitamin B12",
  "Vitamin B Complex",
  "Folic Acid",
  "Iron",
  "Potassium",
  "Glucosamine",
  "Chondroitin",
  "Vitamin C",
  "Vitamin E",
  "Vitamin A",
  "Vitamin K",
  "Vitamin B1",
  "Vitamin B6",
  "Biotin",
  "Zinc",
  "Selenium",
  "Chromium",
  "Probiotics",
  "Melatonin",
  "Turmeric",
  "Ginkgo Biloba",

  // Dermatological (20)
  "Hydrocortisone Cream",
  "Triamcinolone Cream",
  "Betamethasone",
  "Clobetasol",
  "Mupirocin",
  "Clotrimazole",
  "Ketoconazole",
  "Terbinafine",
  "Nystatin",
  "Acyclovir Cream",
  "Tretinoin",
  "Adapalene",
  "Benzoyl Peroxide",
  "Calcipotriene",
  "Tacrolimus",
  "Pimecrolimus",
  "Silver Sulfadiazine",
  "Bacitracin",
  "Neosporin",
  "Lidocaine Cream",

  // Hormone Replacement (15)
  "Estradiol",
  "Conjugated Estrogens",
  "Progesterone",
  "Medroxyprogesterone",
  "Testosterone",
  "Levothyroxine",
  "Synthroid",
  "Armour Thyroid",
  "Cytomel",
  "Liothyronine",
  "Prednisone",
  "Hydrocortisone",
  "Desmopressin",
  "Oxytocin",
  "Vasopressin",

  // Blood Thinners & Related (15)
  "Warfarin",
  "Heparin",
  "Enoxaparin",
  "Apixaban",
  "Rivaroxaban",
  "Dabigatran",
  "Edoxaban",
  "Clopidogrel",
  "Prasugrel",
  "Ticagrelor",
  "Dipyridamole",
  "Cilostazol",
  "Pentoxifylline",
  "Aspirin",
  "Aspirin-Dipyridamole",

  // Gout & Related (10)
  "Allopurinol",
  "Febuxostat",
  "Colchicine",
  "Probenecid",
  "Pegloticase",
  "Indomethacin",
  "Naproxen",
  "Prednisone",
  "Methylprednisolone",
  "Prednisolone",

  // Migraine & Headache (15)
  "Sumatriptan",
  "Rizatriptan",
  "Eletriptan",
  "Zolmitriptan",
  "Almotriptan",
  "Naratriptan",
  "Frovatriptan",
  "Ergotamine",
  "Dihydroergotamine",
  "Topiramate",
  "Propranolol",
  "Amitriptyline",
  "Verapamil",
  "Botox",
  "Aimovig",

  // Nausea & Vomiting (10)
  "Ondansetron",
  "Promethazine",
  "Metoclopramide",
  "Prochlorperazine",
  "Meclizine",
  "Dimenhydrinate",
  "Scopolamine",
  "Doxylamine",
  "Aprepitant",
  "Granisetron",

  // Erectile Dysfunction (5)
  "Sildenafil",
  "Tadalafil",
  "Vardenafil",
  "Avanafil",
  "Alprostadil",

  // Other Common Medications (20)
  "Albuterol Inhaler",
  "Nitroglycerin",
  "Epinephrine",
  "Naloxone",
  "Insulin Pen",
  "Glucose Tablets",
  "Potassium Chloride",
  "Sodium Chloride",
  "Lactose",
  "Simethicone",
  "Activated Charcoal",
  "Cholestyramine",
  "Colestipol",
  "Niacin",
  "Nicotinic Acid",
  "Pancrelipase",
  "Ursodiol",
  "Lactulose",
  "Rifaximin",
  "Eluxadoline",

  // Over-The-Counter Pain Relief (15)
  "Tylenol",
  "Advil",
  "Motrin",
  "Aleve",
  "Excedrin",
  "BC Powder",
  "Goody's Powder",
  "Anacin",
  "Bufferin",
  "Bayer Aspirin",
  "Ecotrin",
  "Midol",
  "Pamprin",
  "Aspercreme",
  "Bengay",

  // OTC Digestive & Stomach (25)
  "Tums",
  "Rolaids",
  "Maalox",
  "Mylanta",
  "Pepto-Bismol",
  "Kaopectate",
  "Imodium",
  "Gas-X",
  "Beano",
  "Lactaid",
  "Prilosec OTC",
  "Prevacid OTC",
  "Nexium OTC",
  "Zantac",
  "Pepcid AC",
  "Tagamet",
  "Miralax",
  "Metamucil",
  "Citrucel",
  "FiberCon",
  "Colace",
  "Dulcolax",
  "Senokot",
  "Ex-Lax",
  "Milk of Magnesia",

  // OTC Cold, Flu & Allergy (30)
  "Claritin",
  "Zyrtec",
  "Allegra",
  "Benadryl",
  "Chlor-Trimeton",
  "Sudafed",
  "Sudafed PE",
  "Mucinex",
  "Robitussin",
  "Delsym",
  "NyQuil",
  "DayQuil",
  "Theraflu",
  "Coricidin",
  "Dimetapp",
  "Triaminic",
  "Vicks VapoRub",
  "Halls Cough Drops",
  "Ricola",
  "Chloraseptic",
  "Cepacol",
  "Afrin",
  "Neo-Synephrine",
  "Flonase",
  "Nasacort",
  "Rhinocort",
  "Saline Nasal Spray",
  "Ocean Nasal Spray",
  "Simply Saline",
  "Zicam",

  // OTC Sleep & Anxiety (10)
  "Unisom",
  "Sominex",
  "Nytol",
  "ZzzQuil",
  "Simply Sleep",
  "Melatonin",
  "Valerian Root",
  "5-HTP",
  "L-Theanine",
  "Rescue Remedy",

  // OTC Eye & Ear Care (15)
  "Visine",
  "Clear Eyes",
  "Rohto",
  "Refresh Tears",
  "Systane",
  "Blink Tears",
  "GenTeal",
  "Tears Naturale",
  "Murine",
  "Debrox",
  "Similasan",
  "Polysporin Eye Drops",
  "Bausch + Lomb",
  "TheraTears",
  "Optive",

  // OTC Topical & Skin Care (25)
  "Neosporin",
  "Bacitracin",
  "Polysporin",
  "Band-Aid",
  "Tegaderm",
  "Aquaphor",
  "Vaseline",
  "Eucerin",
  "CeraVe",
  "Cetaphil",
  "Aveeno",
  "Gold Bond",
  "Cortizone-10",
  "Cortaid",
  "Benadryl Cream",
  "Caladryl",
  "Calamine Lotion",
  "Lotrimin",
  "Lamisil AT",
  "Tinactin",
  "Desenex",
  "Preparation H",
  "Anusol",
  "Tucks",
  "Monistat",

  // Additional Supplements (40)
  "Centrum",
  "One A Day",
  "Nature Made",
  "Kirkland Signature",
  "Vitafusion",
  "Nature's Bounty",
  "Spring Valley",
  "GNC",
  "Solgar",
  "NOW Foods",
  "Garden of Life",
  "Rainbow Light",
  "New Chapter",
  "MegaFood",
  "Country Life",
  "Bluebonnet",
  "Jarrow Formulas",
  "Doctor's Best",
  "Life Extension",
  "Thorne",
  "Pure Encapsulations",
  "Nordic Naturals",
  "Carlson",
  "Nature's Way",
  "Gaia Herbs",
  "Herb Pharm",
  "Planetary Herbals",
  "Solaray",
  "Source Naturals",
  "Swanson",
  "Enzymatic Therapy",
  "Nature's Plus",
  "Twinlab",
  "Natrol",
  "21st Century",
  "Sundown Naturals",
  "Puritan's Pride",
  "Mason Vitamins",
  "Rexall",
  "Walgreens",

  // Herbal Supplements (25)
  "Echinacea",
  "Elderberry",
  "Garlic",
  "Ginger",
  "Ginseng",
  "Green Tea Extract",
  "Milk Thistle",
  "Saw Palmetto",
  "St. John's Wort",
  "Black Cohosh",
  "Red Yeast Rice",
  "Cranberry",
  "Grape Seed Extract",
  "Resveratrol",
  "Astaxanthin",
  "Lutein",
  "Zeaxanthin",
  "Bilberry",
  "Hawthorn",
  "Horse Chestnut",
  "Butcher's Broom",
  "Evening Primrose Oil",
  "Borage Oil",
  "Flaxseed Oil",
  "Chia Seeds",

  // Joint & Bone Support (15)
  "Glucosamine Chondroitin",
  "MSM",
  "Collagen",
  "Hyaluronic Acid",
  "Boswellia",
  "SAM-e",
  "Curcumin",
  "Bromelain",
  "Tart Cherry",
  "Devil's Claw",
  "Willow Bark",
  "Arnica",
  "Comfrey",
  "Bone Meal",
  "Strontium",

  // Heart & Circulation (10)
  "L-Carnitine",
  "L-Arginine",
  "Hawthorn Berry",
  "Nattokinase",
  "Serrapeptase",
  "Horse Chestnut",
  "Ginkgo",
  "Cayenne",
  "Garlic Extract",
  "Red Yeast Rice",

  // Brain & Memory (15)
  "Phosphatidylserine",
  "Acetyl-L-Carnitine",
  "Alpha GPC",
  "Huperzine A",
  "Bacopa Monnieri",
  "Lion's Mane",
  "Rhodiola",
  "Ashwagandha",
  "Holy Basil",
  "L-Tyrosine",
  "DMAE",
  "Vinpocetine",
  "Prevagen",
  "Focus Factor",
  "Neuriva",

  // Digestive Enzymes & Probiotics (15)
  "Acidophilus",
  "Lactobacillus",
  "Bifidobacterium",
  "Culturelle",
  "Align",
  "Florastor",
  "Digestive Advantage",
  "Papaya Enzyme",
  "Bromelain",
  "Betaine HCL",
  "Ox Bile",
  "Lipase",
  "Protease",
  "Amylase",
  "Prebiotics",
];

// Remove duplicates and sort
export const uniqueCommonMedications = Array.from(new Set(commonMedications)).sort();

// Medication-specific dosage mappings (most common dosages for specific medications)
export const medicationDosageMap: { [key: string]: string[] } = {
  // Cardiovascular
  "Lisinopril": ["5 mg", "10 mg", "20 mg", "40 mg"],
  "Atorvastatin": ["10 mg", "20 mg", "40 mg", "80 mg"],
  "Amlodipine": ["2.5 mg", "5 mg", "10 mg"],
  "Metoprolol": ["25 mg", "50 mg", "100 mg", "200 mg"],
  "Losartan": ["25 mg", "50 mg", "100 mg"],
  "Simvastatin": ["10 mg", "20 mg", "40 mg", "80 mg"],
  "Furosemide": ["20 mg", "40 mg", "80 mg"],
  "Aspirin": ["81 mg", "325 mg"],
  "Warfarin": ["1 mg", "2 mg", "2.5 mg", "3 mg", "4 mg", "5 mg", "7.5 mg", "10 mg"],

  // Diabetes
  "Metformin": ["500 mg", "850 mg", "1000 mg"],
  "Glipizide": ["5 mg", "10 mg"],
  "Ozempic": ["0.25 mg injection", "0.5 mg injection", "1 mg injection", "2 mg injection"],
  "Jardiance": ["10 mg", "25 mg"],
  "Insulin Glargine": ["10 units", "20 units", "30 units", "40 units"],

  // Pain & Inflammation
  "Tylenol": ["325 mg", "500 mg", "650 mg", "1 tablet", "2 tablets"],
  "Acetaminophen": ["325 mg", "500 mg", "650 mg"],
  "Ibuprofen": ["200 mg", "400 mg", "600 mg", "800 mg"],
  "Advil": ["200 mg", "1 tablet", "2 tablets"],
  "Naproxen": ["220 mg", "375 mg", "500 mg"],
  "Aleve": ["220 mg", "1 tablet"],
  "Tramadol": ["50 mg", "100 mg"],
  "Gabapentin": ["100 mg", "300 mg", "400 mg", "600 mg", "800 mg"],
  "Prednisone": ["5 mg", "10 mg", "20 mg"],

  // Mental Health
  "Sertraline": ["25 mg", "50 mg", "100 mg"],
  "Escitalopram": ["5 mg", "10 mg", "20 mg"],
  "Zolpidem": ["5 mg", "10 mg"],
  "Melatonin": ["1 mg", "3 mg", "5 mg", "10 mg"],
  "Alprazolam": ["0.25 mg", "0.5 mg", "1 mg"],

  // Thyroid
  "Levothyroxine": ["25 mcg", "50 mcg", "75 mcg", "88 mcg", "100 mcg", "112 mcg", "125 mcg", "137 mcg", "150 mcg"],
  "Synthroid": ["25 mcg", "50 mcg", "75 mcg", "88 mcg", "100 mcg", "112 mcg", "125 mcg"],

  // Gastrointestinal
  "Omeprazole": ["20 mg", "40 mg"],
  "Prilosec OTC": ["20 mg", "1 tablet"],
  "Pantoprazole": ["20 mg", "40 mg"],
  "Pepto-Bismol": ["2 tablespoons", "30 ml"],
  "Miralax": ["17 g", "1 capful"],
  "Tums": ["500 mg", "750 mg", "1000 mg", "2 tablets"],

  // Respiratory
  "Albuterol": ["2 puffs", "90 mcg per puff"],
  "Albuterol Inhaler": ["2 puffs", "90 mcg per puff"],
  "Montelukast": ["10 mg"],
  "Flonase": ["1 spray", "2 sprays"],

  // Vitamins & Supplements
  "Vitamin D": ["1000 IU", "2000 IU", "5000 IU"],
  "Vitamin D3": ["1000 IU", "2000 IU", "5000 IU", "10000 IU"],
  "Calcium": ["500 mg", "600 mg", "1000 mg"],
  "Multivitamin": ["1 tablet", "1 capsule"],
  "Fish Oil": ["1000 mg", "1200 mg", "1 capsule", "2 capsules"],
  "Omega-3": ["1000 mg", "1200 mg", "1 capsule"],
  "Vitamin B12": ["500 mcg", "1000 mcg", "2500 mcg"],
  "Magnesium": ["200 mg", "250 mg", "400 mg", "500 mg"],

  // OTC Allergy
  "Claritin": ["10 mg", "1 tablet"],
  "Zyrtec": ["5 mg", "10 mg", "1 tablet"],
  "Allegra": ["60 mg", "180 mg", "1 tablet"],
  "Benadryl": ["25 mg", "50 mg", "1 tablet", "2 tablets"],
};

// Get dosage suggestions for a specific medication (prioritizes medication-specific dosages)
export function getDosageSuggestionsForMedication(medicationName: string, searchTerm: string = ""): string[] {
  const normalizedMedName = medicationName.trim();

  // Get medication-specific dosages if available
  const specificDosages = medicationDosageMap[normalizedMedName] || [];

  // Filter common dosages based on search term
  const filteredCommonDosages = searchTerm
    ? commonDosages.filter(d => d.toLowerCase().includes(searchTerm.toLowerCase()))
    : commonDosages;

  // Combine: specific dosages first, then remaining common dosages
  const allDosages = [
    ...specificDosages,
    ...filteredCommonDosages.filter(d => !specificDosages.includes(d))
  ];

  // If there's a search term, filter the combined list
  if (searchTerm) {
    return allDosages.filter(d => d.toLowerCase().includes(searchTerm.toLowerCase()));
  }

  return allDosages;
}

// Common dosages (90+ options - expanded with more liquid and syringe measurements)
export const commonDosages = [
  // Milligrams - very small doses
  "0.25 mg",
  "0.5 mg",
  "0.75 mg",
  "1 mg",
  "1.25 mg",
  "1.5 mg",
  "2 mg",
  "2.5 mg",
  "3 mg",
  "4 mg",
  "5 mg",
  "6 mg",
  "7.5 mg",
  "8 mg",
  "10 mg",
  "12.5 mg",
  "15 mg",
  "20 mg",
  "25 mg",
  "30 mg",
  "37.5 mg",
  "40 mg",
  "50 mg",
  "60 mg",
  "75 mg",
  "80 mg",
  "100 mg",
  "125 mg",
  "150 mg",
  "175 mg",
  "200 mg",
  "250 mg",
  "300 mg",
  "325 mg",
  "400 mg",
  "500 mg",
  "600 mg",
  "650 mg",
  "750 mg",
  "800 mg",
  "850 mg",
  "1000 mg",

  // Micrograms
  "25 mcg",
  "50 mcg",
  "75 mcg",
  "88 mcg",
  "100 mcg",
  "112 mcg",
  "125 mcg",
  "137 mcg",
  "150 mcg",
  "175 mcg",
  "200 mcg",
  "300 mcg",

  // Tablets/Capsules
  "0.5 tablet",
  "1 tablet",
  "1.5 tablets",
  "2 tablets",
  "3 tablets",
  "4 tablets",
  "1 capsule",
  "2 capsules",
  "3 capsules",
  "4 capsules",

  // Liquids (ml and volume measurements)
  "0.5 ml",
  "1 ml",
  "2 ml",
  "2.5 ml",
  "5 ml",
  "7.5 ml",
  "10 ml",
  "12.5 ml",
  "15 ml",
  "20 ml",
  "25 ml",
  "30 ml",
  "1 teaspoon",
  "1/2 teaspoon",
  "1.5 teaspoons",
  "2 teaspoons",
  "1 tablespoon",
  "1.5 tablespoons",
  "2 tablespoons",

  // Insulin and Syringes (units)
  "5 units",
  "10 units",
  "12 units",
  "15 units",
  "20 units",
  "25 units",
  "30 units",
  "35 units",
  "40 units",
  "45 units",
  "50 units",
  "60 units",
  "70 units",
  "80 units",
  "100 units",

  // IU (International Units) for vitamins
  "400 IU",
  "800 IU",
  "1000 IU",
  "2000 IU",
  "3000 IU",
  "5000 IU",
  "10000 IU",

  // Inhalers/Sprays
  "1 puff",
  "2 puffs",
  "3 puffs",
  "4 puffs",
  "1 spray",
  "2 sprays",
  "3 sprays",

  // Drops
  "1 drop",
  "2 drops",
  "3 drops",
  "4 drops",

  // Other
  "1 patch",
  "1 injection",
  "Apply as directed",
];

export type MedicationFrequency =
  | "daily"
  | "twice-daily"
  | "three-times-daily"
  | "four-times-daily"
  | "every-other-day"
  | "weekly"
  | "biweekly"
  | "monthly"
  | "quarterly"
  | "yearly"
  | "one-time"
  | "as-needed";

export type TimeOfDay = "morning" | "afternoon" | "evening" | "night" | "specific";

export const frequencyOptions = [
  // Daily options
  { value: "daily" as const, label: "Once daily", description: "Take once every day" },
  { value: "twice-daily" as const, label: "Twice daily", description: "Take 2 times per day" },
  { value: "three-times-daily" as const, label: "Three times daily", description: "Take 3 times per day" },
  { value: "four-times-daily" as const, label: "Four times daily", description: "Take 4 times per day" },

  // Less frequent
  { value: "every-other-day" as const, label: "Every other day", description: "Take every 2 days" },
  { value: "weekly" as const, label: "Weekly", description: "Take once a week" },
  { value: "biweekly" as const, label: "Every 2 weeks", description: "Take every 2 weeks" },
  { value: "monthly" as const, label: "Monthly", description: "Take once a month" },
  { value: "quarterly" as const, label: "Every 3 months", description: "Take 4 times per year" },
  { value: "yearly" as const, label: "Yearly", description: "Take once a year" },

  // Special
  { value: "one-time" as const, label: "One time only", description: "Single dose (e.g., vaccine)" },
  { value: "as-needed" as const, label: "As needed (PRN)", description: "Take when needed" },
];

export const timeOfDayOptions = [
  { value: "morning" as const, label: "Morning", defaultTime: "08:00" },
  { value: "afternoon" as const, label: "Afternoon", defaultTime: "14:00" },
  { value: "evening" as const, label: "Evening", defaultTime: "18:00" },
  { value: "night" as const, label: "Night", defaultTime: "21:00" },
  { value: "specific" as const, label: "Specific time", defaultTime: "09:00" },
];
